<a href="https://colab.research.google.com/github/Praneethgajula01/aml-0026/blob/main/aml_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'Classroom',
 '22X31A0571(Gajula.Praneeth).jpg',
 'Gajula Praneeth (1).pdf',
 'ce14e92b-c7dd-4b46-b9b5-ba460ed95437.jpg',
 'Untitled document (2).gdoc',
 "Praneeth's edits",
 'Copy of Picsart_24-10-21_19-24-00-206 (2).jpg',
 'Copy of Picsart_24-10-21_19-24-00-206 (1).jpg',
 'Copy of Picsart_24-10-21_19-24-00-206.jpg',
 'Praneeth Resume.pdf',
 'WhatsApp Image 2025-07-22 at 18.49.37.jpeg',
 'Untitled.gdoc',
 '8e404cec-eaf3-49f2-9d2c-2334c0ead5d3.pdf',
 'Untitled spreadsheet.xlsx',
 'Untitled spreadsheet.gsheet',
 'chitsmake (1).docx',
 'chit spreadsheet.gsheet',
 'Untitled document (1).gdoc',
 'Copy of Untitled document.gdoc',
 'Screenshot 2025-09-18 120628.png',
 'image (1).pdf',
 'image.pdf',
 'in easiest way make me understand about static in....gsheet',
 'Annotations:\nKnowing what an annotation is and ho....gsheet',
 'praneethgajularox@gmail.com  9398245232  Hyderabad,Telangana500059 (1) (1) (1).pdf',
 'praneethgajularox@gmail.com  9398245232  Hyderabad,Telangana500059 (1) (1).pdf',
 'praneethgajularox@gmail.com  9398245232  Hyderabad,Telangana500059 (1) (1).pdf.pdf',
 '1759557212164.jpg',
 '1759563099462.jpg',
 'github.pdf',
 'python.pdf',
 'java.pdf',
 'praneeth_resume (1) (2).pdf',
 'praneeth_resume (1) (1).pdf',
 'praneeth_resume (1).pdf',
 'ConfirmationPage-265710371212.pdf',
 'Praneeth Gajula.pdf',
 'Google AI Studio',
 'Praneeth Gajula (1).pdf',
 'Praneeth Gajula resume (3).pdf',
 'Praneeth Gajula resume (2).pdf',
 'Praneeth Gajula resume.pdf',
 'Praneeth Gajula resume.gdoc',
 'Praneeth Gajula resume.pdf.pdf',
 'Praneeth Gajula resume (1).pdf',
 'Document from Praneeth.pdf',
 'LinkedIn Tracker.gsheet',
 'Untitled document.gdoc',
 'M- Praneeth - 0571.jpg',
 'M - PRANEETH - 0571.jpg',
 'Sri Rama Cell Care - Form Submissions.gsheet',
 'DSA_AIML_Theory_shared.pdf',
 'WhatsApp Image 2026-08-10 at 20.21.35.jpeg',
 'bestsellers.csv',
 'Data.csv',
 'Groceries_dataset.csv',
 'bestsellers with categories.csv',
 'Data.gsheet']

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Data.csv')
display(dataset.head())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
dataset.isnull().sum()

NameError: name 'dataset' is not defined

In [ ]:
X=dataset.iloc[:, :-1]
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y=dataset.iloc[:, 1]
y

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")
imputer=imputer.fit(X.iloc[:, 1:3])
X.iloc[:, 1:3]=imputer.transform(X.iloc[:, 1:3])

X

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
X[:, 0]=labelencoder_X.fit_transform(X[:, 0])
X

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.40000000e+01, 7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.00000000e+01, 5.40000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.50000000e+01, 5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.70000000e+01, 6.70000000e+04]])

In [ ]:
#encoding the independent variables

from sklearn.compose import ColumnTransformer

ct=ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder="passthrough")
X=ct.fit_transform(X)
X.astype(int)

array([[    0,     1,     0,     0,    44, 72000],
       [    1,     0,     0,     1,    27, 48000],
       [    1,     0,     1,     0,    30, 54000],
       [    1,     0,     0,     1,    38, 61000],
       [    1,     0,     1,     0,    40, 63777],
       [    0,     1,     0,     0,    35, 58000],
       [    1,     0,     0,     1,    38, 52000],
       [    0,     1,     0,     0,    48, 79000],
       [    1,     0,     1,     0,    50, 83000],
       [    0,     1,     0,     0,    37, 67000]])

In [ ]:
#dependant variables

label_encoder_y=LabelEncoder()
y=label_encoder_y.fit_transform(y)
y
y

array([6, 0, 1, 4, 5, 2, 9, 7, 8, 3])

In [ ]:
# split data into training set and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
#feature scaling


#src_x=(X[1]mean)/standard deviation

from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

X_test

array([[ 1.        , -1.        ,  2.64575131, -0.77459667, -1.45882927,
        -0.90166297],
       [ 1.        , -1.        ,  2.64575131, -0.77459667,  1.98496442,
         2.13981082]])